=== Anil1111/ASP.NET-tutorial-for-beginners-Urdu-Hindi/Lecture 20/DTD & XSD/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Code" type="xs:integer"></xs:element>
							<xs:element name="FirstName" type="xs:string"></xs:element>
							<xs:element name="LastName" type="xs:string"></xs:element>
							<xs:element name="Salary" type="xs:double"></xs:element>
							<xs:element name="Designation" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Anil1111/ASP.NET-tutorial-for-beginners-Urdu-Hindi/Lecture 20/DTD & XSD/Employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Asif/Desktop/employees.xsd">
	<Employee>
		<Code>1</Code>
		<FirstName/>
		<LastName/>
		<Salary>34</Salary>
		<Designation/>
	</Employee>
	<Employee>
		<Code>2</Code>
		<FirstName/>
		<LastName/>
		<Salary>33</Salary>
		<Designation/>
	</Employee>
	<Employee>
		<Code>3</Code>
		<FirstName/>
		<LastName/>
		<Salary>44</Salary>
		<Designation/>
	</Employee>
	<Employee>
		<Code>4</Code>
		<FirstName/>
		<LastName/>
		<Salary>55</Salary>
		<Designation/>
	</Employee>
</Employees>
